name: Merge image variants
on:
  push:
    branches:
      - master
      - test/merge-variants
jobs:
  merge:
    if: github.repository == 'itzg/docker-minecraft-server'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          git config --add user.name "${GITHUB_ACTOR:-Github Actions}"
          git config --add user.email "actions@github.com"
          ls -l
          ls -l /bin/bash
